steps:
  # 1단계 => docker-compose -f docker-compose.prod.yaml build
  - name: docker/compose:1.29.0
    args:
      - -f
      - docker-compose.prod.yaml
      - build

  # 2단계 => docker-compose -f docker-compose.prod.yaml push
  - name: docker/compose:1.29.0
    args:
      - -f
      - main-project/backend/docker-compose.prod.yaml
      - push

  # 3단계 => kubectl set image deployment/mybackend10-nestjs mybackend10-nestjs-sha256-1=asia.gcr.io/eternal-impulse-370212/mybackend10-nestjs:1.7
  - name: gcr.io/cloud-builders/kubectl
    args:
      - set
      - image
      - deployment/mybackend10-nestjs
      - mybackend10-nestjs-sha256-1=asia.gcr.io/eternal-impulse-370212/mybackend10-nestjs:2.2
    env:
      - CLOUDSDK_COMPUTE_ZONE=asia-northeast3
      - CLOUDSDK_CONTAINER_CLUSTER=autopilot-cluster-1
